import * as loginPage from '../support/Base/pages/Login.po';
import { LoginInvoicePageData } from '../support/Base/pagedata/LoginInvoicePageData';
import * as invoicesPage from '../support/Base/pages/Invoices.po';
import { InvoicesPageData } from '../support/Base/pagedata/InvoicesPageData';
import * as dashboardPage from '../support/Base/pages/Dashboard.po';
import { CustomCommands } from '../support/commands';

describe('Invoices test', { testIsolation: false }, () => {
	before(() => {
		CustomCommands.login(loginPage, LoginInvoicePageData, dashboardPage);
		cy.visit('/#/pages/accounting/invoices');
	});
	it('Should be able to add new invoice', () => {
		invoicesPage.addButtonVisible();
		invoicesPage.clickAddButton();
		invoicesPage.clickCardBody();
		invoicesPage.discountInputVisible();
		invoicesPage.enterDiscountData(InvoicesPageData.discountValue);
		invoicesPage.discountTypeDropdownVisible();
		invoicesPage.clickDiscountDropdown();
		invoicesPage.selectDiscountTypeFromDropdown(InvoicesPageData.discountType);
		invoicesPage.taxInputVisible();
		invoicesPage.enterTaxData(InvoicesPageData.taxValue);
		invoicesPage.taxTypeDropdownVisible();
		invoicesPage.clickTaxTypeDropdown();
		invoicesPage.selectTaxTypeFromDropdown(InvoicesPageData.taxType);
		invoicesPage.invoiceTypeDropdownVisible();
		invoicesPage.clickInvoiceTypeDropdown();
		invoicesPage.selectInvoiceTypeFromDropdown(InvoicesPageData.invoiceType);
		invoicesPage.employeeDropdownVisible();
		invoicesPage.generateItemsButtonVisible();
		invoicesPage.clickGenerateItemsButton();
		invoicesPage.saveAsDraftButtonVisible();
		invoicesPage.clickSaveAsDraftButton(InvoicesPageData.saveAsDraftButton);
		invoicesPage.waitMessageToHide();
		invoicesPage.verifyDraftBadgeClass();
	});
	it('Should be able to search invoice', () => {
		invoicesPage.verifyTabButtonVisible();
		invoicesPage.clickTabButton(1);
		invoicesPage.verifyEstimateNumberInputVisible();
		invoicesPage.enterEstimateNumberInputData(InvoicesPageData.invoiceNumber);
		invoicesPage.verifyCurrencyDropdownVisible();
		invoicesPage.verifyEstimateDateInput();
		invoicesPage.verifyEstimateDueDateInput();
		invoicesPage.verifyTotalValueInputVisible();
		invoicesPage.verifyCurrencyDropdownVisible();
		invoicesPage.verifyStatusInputVisible();
		invoicesPage.searchButtonVisible();
		invoicesPage.clickSearchButton();
		invoicesPage.resetButtonVisible();
		invoicesPage.clickResetButton();
		invoicesPage.clickSearchButton();
		invoicesPage.verifyDraftBadgeClass();
		invoicesPage.enterEstimateNumberInputData(InvoicesPageData.secondInvoiceNumber);
		invoicesPage.clickSearchButton();
		invoicesPage.clickResetButton();
		invoicesPage.verifyDraftBadgeClass();
		invoicesPage.clickTabButton(2);
		invoicesPage.verifyDraftBadgeClass();
	});
	it('Should be able to edit invoice', () => {
		invoicesPage.clickTabButton(0);
		invoicesPage.selectTableRow(0);
		invoicesPage.editButtonVisible();
		invoicesPage.clickEditButton(0);
		invoicesPage.discountInputVisible();
		invoicesPage.enterDiscountData(InvoicesPageData.editDiscountValue);
		invoicesPage.discountTypeDropdownVisible();
		invoicesPage.clickDiscountDropdown();
		invoicesPage.selectDiscountTypeFromDropdown(InvoicesPageData.discountType);
		invoicesPage.taxInputVisible();
		invoicesPage.enterTaxData(InvoicesPageData.taxValue);
		invoicesPage.taxTypeDropdownVisible();
		invoicesPage.clickTaxTypeDropdown();
		invoicesPage.selectTaxTypeFromDropdown(InvoicesPageData.taxType);
		invoicesPage.saveAsDraftButtonVisible();
		invoicesPage.clickSaveAsDraftButton(InvoicesPageData.saveAsDraftButton);
		invoicesPage.waitMessageToHide();
		invoicesPage.verifyDraftBadgeClass();
	});
	it('Should be able to view invoice', () => {
		invoicesPage.selectTableRow(0);
		invoicesPage.viewButtonVisible();
		invoicesPage.clickViewButton();
		invoicesPage.backButtonVisible();
		invoicesPage.clickBackButton();
	});
	it('Should be able to set invoice status', () => {
		invoicesPage.selectTableRow(0);
		invoicesPage.openStatusDropdown();
		invoicesPage.selectStatus(InvoicesPageData.status);
	});
	it('Should be able to delete invoice', () => {
		invoicesPage.waitMessageToHide();
		invoicesPage.selectTableRow(0);
		invoicesPage.clickDeleteButton();
		invoicesPage.confirmDeleteButtonVisible();
		invoicesPage.clickConfirmDeleteButton();
		invoicesPage.waitMessageToHide();
		invoicesPage.verifyElementIsDeleted();
	});
});
