export const AddEmployeePositionPage = {
	gridButtonCss: 'div.layout-switch > button',
	addNewPositionButtonCss: 'button[status="success"]',
	newPositionInputCss: '[placeholder="Position name"]',
	tagsSelectCss: 'nb-dialog-container ng-select#addTags>div>span',
	tagsSelectOptionCss: '[type="checkbox"]',
	saveNewPositionButtonCss: 'button[status="success"]',
	updatePositionButtonCss: 'button[status="success"]',
	cancelNewPositionButtonCss: 'button.delete.mr-3',
	editEmployeePositionButtonCss: 'button.action.primary',
	removeEmployeePositionButtonCss: 'button.action.appearance-filled',
	confirmDeletePositionButtonCss: 'ga-delete-confirmation nb-card-footer button[status="danger"]',
	editPositionInputCss: 'div.d-flex > input[type="text"]',
	verifyTextCss: 'ga-notes-with-tags > div > div > div.ng-star-inserted',
	cardBodyCss: 'nb-card-body',
	toastrMessageCss: 'nb-toast.ng-trigger',
	cancelButtonCss: 'button.delete.mr-3',
	selectPositionToEditCss: 'ga-notes-with-tags',
	selectPositionToDeleteCss: 'ga-notes-with-tags',
	positionTableCss: 'nb-card-body.custom-table'
};
