export const ClientsPage = {
	gridButtonCss: 'div.layout-switch > button',
	addButtonCss: 'button[nbbutton][status="success"]:contains("Add")',
	editButtonCss: 'div.mb-3 > button[status="success"]',
	inviteButtonCss: 'div.mb-3 > button[status="primary"]',
	deleteButtonCss: 'div.mb-3 > button[status="danger"]',
	nameInputCss: '#name',
	emailInputCss: '#email',
	lastStepBtnCss: 'div.step-content > form > div > button[status="success"]',
	phoneInputCss: '[formcontrolname="primaryPhone"]',
	budgetInputCss: 'input[formcontrolname="budget"]',
	countryDropdownCss: 'ga-country ng-select',
	cityInputCss: '[formcontrolname="city"]',
	postCodeInputCss: '[formcontrolname="postcode"]',
	streetInputCss: '[formcontrolname="address"]',
	projectsDropdownCss: 'ng-select[formcontrolname="projects"] .ng-select-container',
	projectsDropdownOptionCss: 'div.ng-dropdown-panel-items',
	usersMultiSelectCss: 'div.form-group ga-employee-multi-select nb-select',
	usersDropdownOptionCss: 'nb-option-list ul.option-list',
	dropdownOptionCss: '.ng-dropdown-panel .ng-option',
	addTagsDropdownCss: '#addTags .ng-input input',
	tagsDropdownOption: 'div.ng-dropdown-panel-items div.ng-option',
	websiteInputCss: '[formcontrolname="website"]',
	cardBodyCss: 'div.contact-container',
	saveButtonCss: 'button[nbsteppernext][status="success"]',
	nextButtonCss: 'div.buttons button:contains("Next")',
	nextGroupButtonCss: 'button[nbsteppernext]',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	clientNameCss: '[formcontrolname="name"]',
	clientPhoneCss: '[formcontrolname="primaryPhone"]',
	clientEmailCss: '#emailInput',
	toastrMessageCss: 'nb-toast.ng-trigger',
	saveInviteButtonCss: 'nb-card-footer > button[status="success"]',
	verifyClientCss: 'div.names-wrapper',
	searchNameInputCss: 'input[placeholder="Name"]',
	clientsTableData: 'td.ng-star-inserted',
	clientsTableRow: 'tr[class="angular2-smart-row ng-star-inserted"]',
	viewButtonCss: 'div.mb-3 > button[status="info"]',
	clientNameViewCss: 'div.profile-user-title-name',
	clientTypeViewCss: 'div.profile-user-title-type',
	backBtn: 'ngx-back-navigation > div > button[status="primary"]'
};
