export const EditEmployeePage = {
	employeeCss: 'div.block-info > div.row > div.col',
	editButtonCss: 'nb-icon.edit-icon',
	usernameInputCss: '#usernameInput',
	tabButtonCss: 'ul.route-tabset > li.route-tab',
	tabCss: 'a.tab-link',
	firstNameInputCss: '#firstNameInput',
	lastNameInputCss: '#lastNameInput',
	emailInputCss: '#emailInput',
	preferredLanguageCss: 'div.col-sm-6 > div.form-group > ngx-language-selector > ng-select .ng-input > input',
	preferredLanguageOptionCss: 'ng-dropdown-panel.ng-dropdown-panel > div.ng-dropdown-panel-items div.ng-option',
	dropdownOptionCss: '.ng-dropdown-panel .ng-option',
	dropdownOptionAnotherCss: 'nb-option',
	linkedInInputCss: '#linkedIn',
	githubInputCss: '#github',
	upworkInputCss: '#upwork',
	descriptionInputCss: '#shortDescription',
	offerDateInputCss: '#offerDateInput',
	acceptDateInputCss: '#acceptDateInput',
	countryDropdownCss: 'ga-country ng-select input[role="combobox"]',
	cityInputCss: '#cityInput',
	postCodeInputCss: '#postcodeInput',
	addressInputCss: '#addressInput',
	payPeriodDropdownCss: '#payPeriodsSelect',
	weeklyLimitInputCss: '#reWeeklyLimitInput',
	billRateValueInputCss: '#billRateValueInput',
	projectOrContactsDropdownCss: '#departmentsSelect input',
	projectOrContactDropdownOptionCss: '.ng-dropdown-panel .ng-option',
	addProjectOrContactButtonCss: 'nb-card-header > button[status="success"]',
	saveProjectOrContactButtonCss: 'button.status-success',
	verifyProjectOrContactCss: 'nb-card.ng-star-inserted > nb-card-body',
	saveButtonCss: 'div.actions > button[status="success"]',
	verifyEmployeeCss: 'span.employee-name',
	toastrMessageCss: 'nb-toast.ng-trigger'
};
