export const InvoicesPage = {
	selectStatusOptionCss: 'nb-option',
	tabButtonCss: 'ul.tabset li.tab',
	editButtonCss: 'div.actions-container button:contains("Edit")',
	setStatusButtonCss: 'div.actions-container nb-select button.select-button',
	viewButtonCss: 'button.action.secondary[nbbutton][status="basic"]',
	deleteButtonCss: 'button nb-icon[ng-reflect-icon="trash-2-outline"]',
	discountInputCss: '#inputDiscountValue',
	discountTypeDropdownCss: '[formcontrolname="discountType"]',
	dropdownOptionCss: '.option-list nb-option',
	taxInputCss: '#inputTax',
	taxTypeDropdownCss: '[formcontrolname="taxType"]',
	invoiceTypeDropdownCss: '[formcontrolname="invoiceType"]',
	generateItemsButtonCss: 'div.buttons > button[status="basic"]',
	selectEmployeeCss: 'div.form-group > input[formcontrolname="selectedEmployee"]',
	saveAsDraftButtonCss: 'nb-card-footer > button[status="success"]',
	emailInputCss: '#email',
	tableRowCss: 'table > tbody > tr.angular2-smart-row',
	toastrMessageCss: 'nb-toast.ng-trigger',
	cardBodyCss: 'nb-card-header.d-flex',
	backButtonCss: 'button i.fas.fa-arrow-left',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	verifyInvoiceCss: 'tr.ng-star-inserted > td',
	draftBadgeCss: 'div.badge-warning',
	emailCardCss: 'nb-card-body.invoice-email-body',
	inputInvoiceNumberCss: '#inputInvoiceNumber',
	estimateDateCss: '#inputInvoiceDate',
	dueDateInputCss: '#inputDueDate',
	totalValueInputCss: '#inputTotalValue',
	currencySelectCss: 'ga-currency .ng-select-container',
	inputStatusCss: '#inputStatus',
	searchButtonCss: 'div.row > div > button[status="success"]',
	resetButtonCss: 'div.row > div > button[status="basic"]',
	openStatusDropdownCss: 'nb-select[ng-reflect-placeholder="Set Status"] button.select-button',
	actionsBarCss: '.transition-container',
	addButtonName: 'Add'
};
