export const ManageUserInvitesPage = {
	manageInvitesButtonCss: 'div.card-header-title > button[status="primary"]',
	gridButtonCss: 'div.layout-switch > button',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	copyLinkButtonCss: 'div.btn-group.actions button.action.success',
	addInviteButtonCss: 'button[status="success"]',
	resendInviteButtonCss: 'div.btn-group.actions button.action.warning',
	deleteInviteButtonCss: 'button nb-icon[icon="trash-2-outline"]',
	confirmResendInviteButtonCss: 'nb-card-footer > button[status="success"]',
	confirmDeleteInviteButtonCss: 'nb-card-footer > button[status="danger"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	inviteButtonCss: 'nb-card-footer button[status="success"]',
	emailInputCss: '#emails',
	dateInputCss: 'input[formcontrolname="startedWorkOn"]',
	verifyEmailCss: 'table-cell-view-mode > div > div.ng-star-inserted',
	rolesInputCss: 'nb-select[ng-reflect-placeholder="Select Role"]',
	dropdownCss: 'nb-option',
	clientsTableData: 'td.ng-star-inserted',
	clientsTableRow: 'tr[class="angular2-smart-row ng-star-inserted"]',
	invitationExpirationSelectCss: 'nb-select#invitationExpirationPeriod > button.select-button'
};
