export const TimesheetsPage = {
	addTimeButtonCss: 'button.action.status-success[status="success"]',
	selectEmployeeCss: 'ga-employee-multi-select[formcontrolname="employeeId"] > nb-select',
	selectEmployeeDropdownOptionCss: '.option-list nb-option',
	dateInputCss: '[name="date"]',
	projectDropdownCss: '[formControlName="projectId"] .ng-input input',
	dropdownOptionCss: 'div.ng-option',
	clientDropdownCss: '[formcontrolname="organizationContactId"] .ng-input input',
	clientDropdownOptionCss: 'div.ng-dropdown-panel-items .ng-option',
	taskDropdownCss: '[formcontrolname="taskId"] .ng-input input',
	descriptionTextareaCss: 'textarea[name="description"]',
	saveTimeButtonCss: 'nb-card-footer button[status="success"]',
	viewEmployeeTimeCss: 'button[nbbutton][status="basic"]:contains("View")',
	editEmployeeTimeCss: 'button[nbbutton][status="basic"].primary:contains("Edit")',
	deleteEmployeeTimeCss: 'button[nbbutton][status="basic"] nb-icon[icon="trash-2-outline"]',
	closeAddTimeLogPopoverCss: 'span.cancel i.fas.fa-times',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="primary"]',
	startTimeDropdownCss: 'ga-timer-picker[name="start_time"]',
	closeButtonCss: 'button.close-button',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyTimeCss: 'ngx-avatar > div > div.col > div.ng-star-inserted',
	selectTableRowCss: 'div.custom-body .row.m-0.py-3.align-items-center'
};
